### ISSUE TITLE
Bundler Says error installing nokogiri

### ISSUE THREAD

**Issue by mikemcguire** [cogitatio/vagrant-hostsupdater#70]
Sorry I am not sure if this is an issue with this repo or with bundler itself, but..
Getting an error installing "An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling."

I ran "gem install nokogiri -v '1.6.6.2'" and it installed just fine. I would assume since it's already installed bundler shouldn't even try to install but I keep getting this error. I originally had to recompile ruby with openssl as I was getting an issue with installing nokogiri this way as well.

**Comment by thom8** [comment]
I'm also having installation issues --

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not find gem 'vagrant-hostupdater (>= 0) ruby' in the gems available on this machine.

Vagrant :: 1.7.2
Ruby :: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by mikemcguire** [comment]
This appears to be a known issue with Vagrant https://github.com/mitchellh/vagrant/issues/3769
I tried a couple of things but I am pretty sure upgrading my vagrant bin fixed the issue, as well I uninstalled and reinstalled ruby 1.9.3 via rvm. 
@thom8 you're issue looks unrelated and you may want to open an new issue as I am marking this as closed. I've heard of people have fixed a similar issue to yours by just upgrading bundler. Also make sure your gem sources actually have that gem, you can see your current sources by running ```gem sources```
